/* eslint-disable react-refresh/only-export-components */

import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    appName: "EaseFarmer",
    tagline: "Smart decisions for better farming",
    selectLanguage: "Select Your Language",
    continue: "Continue",
    changeAnytime: "You can change language anytime in settings",
    login: "Login",
    phoneNumber: "Phone Number",
    enterPhone: "Enter your 10-digit phone number",
    sendOTP: "Send OTP",
    enterOTP: "Enter OTP",
    otpSent: "OTP sent to your phone",
    verify: "Verify & Continue",
    dataSecure: "Your data is secure with us",
    selectRole: "I am a",
    farmer: "Farmer",
    trader: "Trader",
    namaste: "Namaste",
    todayWeather: "Today's Weather",
    soilStatus: "Soil Status",
    marketSnapshot: "Market Prices",
    quickActions: "Quick Actions",
    joinMarket: "Join Market Room",
    checkWeather: "Check Weather",
    soilIrrigation: "Soil & Irrigation",
    marketPrices: "Market Prices",
    financeManager: "Finance Manager",
    home: "Home",
    market: "Market",
    weather: "Weather",
    finance: "Finance",
    profile: "Profile",
    activeTraders: "Active Traders",
    highestBid: "Highest Bid",
    perQuintal: "per quintal",
    joinRoom: "Join Room",
    liveBids: "Live Bids",
    placeBid: "Place Bid",
    yourContribution: "Your Contribution",
    profitDistribution: "Profit Distribution",
    transparency: "100% Transparent",
    hourlyForecast: "Hourly Forecast",
    weekForecast: "7-Day Forecast",
    alerts: "Alerts",
    offlineCached: "Offline data available",
    soilMoisture: "Soil Moisture",
    low: "Low",
    optimal: "Optimal", 
    high: "High",
    irrigateNow: "Irrigate Now",
    waitHours: "Wait 6 hours",
    fertilizerTip: "Fertilizer Suggestion",
    trends: "Trends",
    mandiPrices: "Mandi Prices",
    pricePredict: "Price Prediction",
    compared: "compared to yesterday",
    confidence: "Confidence",
    loans: "Your Loans",
    amountBorrowed: "Amount Borrowed",
    interestRate: "Interest Rate",
    nextEMI: "Next EMI Date",
    govtSchemes: "Government Schemes",
    bankLoans: "Bank Loan Options",
    settings: "Settings",
    changeLanguage: "Change Language",
    notifications: "Notifications",
    iotStatus: "IoT Device Status",
    helpSupport: "Help & Support",
    logout: "Logout",
    connected: "Connected",
    notConnected: "Not Connected",
    rainAlert: "Rain expected tomorrow",
    delayIrrigation: "Delay irrigation",
    heatAlert: "High temperature expected",
    protectCrops: "Protect crops with shade nets"
  },
  te: {
    appName: "ఈజ్‌ఫార్మర్",
    tagline: "మంచి వ్యవసాయం కోసం తెలివైన నిర్ణయాలు",
    selectLanguage: "మీ భాషను ఎంచుకోండి",
    continue: "కొనసాగించు",
    changeAnytime: "మీరు ఎప్పుడైనా సెట్టింగ్స్‌లో భాషను మార్చవచ్చు",
    login: "లాగిన్",
    phoneNumber: "ఫోన్ నంబర్",
    enterPhone: "మీ 10 అంకెల ఫోన్ నంబర్ నమోదు చేయండి",
    sendOTP: "OTP పంపండి",
    enterOTP: "OTP నమోదు చేయండి",
    otpSent: "మీ ఫోన్‌కు OTP పంపబడింది",
    verify: "ధృవీకరించి కొనసాగించండి",
    dataSecure: "మీ డేటా మాతో సురక్షితంగా ఉంది",
    selectRole: "నేను ఒక",
    farmer: "రైతు",
    trader: "వ్యాపారి",
    namaste: "నమస్కారం",
    todayWeather: "నేటి వాతావరణం",
    soilStatus: "నేల స్థితి",
    marketSnapshot: "మార్కెట్ ధరలు",
    quickActions: "త్వరిత చర్యలు",
    joinMarket: "మార్కెట్ రూమ్‌లో చేరండి",
    checkWeather: "వాతావరణం చూడండి",
    soilIrrigation: "నేల & నీటిపారుదల",
    marketPrices: "మార్కెట్ ధరలు",
    financeManager: "ఆర్థిక నిర్వాహకుడు",
    home: "హోమ్",
    market: "మార్కెట్",
    weather: "వాతావరణం",
    finance: "ఆర్థికం",
    profile: "ప్రొఫైల్",
    activeTraders: "యాక్టివ్ వ్యాపారులు",
    highestBid: "అత్యధిక బిడ్",
    perQuintal: "క్వింటాల్‌కు",
    joinRoom: "రూమ్‌లో చేరండి",
    liveBids: "లైవ్ బిడ్‌లు",
    placeBid: "బిడ్ చేయండి",
    yourContribution: "మీ సహకారం",
    profitDistribution: "లాభ పంపిణీ",
    transparency: "100% పారదర్శకం",
    hourlyForecast: "గంటల అంచనా",
    weekForecast: "7 రోజుల అంచనా",
    alerts: "హెచ్చరికలు",
    offlineCached: "ఆఫ్‌లైన్ డేటా అందుబాటులో ఉంది",
    soilMoisture: "నేల తేమ",
    low: "తక్కువ",
    optimal: "సరైన",
    high: "ఎక్కువ",
    irrigateNow: "ఇప్పుడు నీరు పెట్టండి",
    waitHours: "6 గంటలు ఆగండి",
    fertilizerTip: "ఎరువు సూచన",
    trends: "ట్రెండ్స్",
    mandiPrices: "మండి ధరలు",
    pricePredict: "ధర అంచనా",
    compared: "నిన్నతో పోలిస్తే",
    confidence: "విశ్వసనీయత",
    loans: "మీ రుణాలు",
    amountBorrowed: "అప్పు తీసుకున్న మొత్తం",
    interestRate: "వడ్డీ రేటు",
    nextEMI: "తదుపరి EMI తేదీ",
    govtSchemes: "ప్రభుత్వ పథకాలు",
    bankLoans: "బ్యాంక్ రుణ ఎంపికలు",
    settings: "సెట్టింగ్స్",
    changeLanguage: "భాష మార్చండి",
    notifications: "నోటిఫికేషన్లు",
    iotStatus: "IoT పరికర స్థితి",
    helpSupport: "సహాయం & మద్దతు",
    logout: "లాగ్అవుట్",
    connected: "కనెక్ట్ అయింది",
    notConnected: "కనెక్ట్ కాలేదు",
    rainAlert: "రేపు వర్షం అంచనా",
    delayIrrigation: "నీటిపారుదల ఆలస్యం చేయండి",
    heatAlert: "అధిక ఉష్ణోగ్రత అంచనా",
    protectCrops: "షేడ్ నెట్లతో పంటలను రక్షించండి"
  },
  hi: {
    appName: "ईज़फार्मर",
    tagline: "बेहतर खेती के लिए स्मार्ट निर्णय",
    selectLanguage: "अपनी भाषा चुनें",
    continue: "जारी रखें",
    changeAnytime: "आप कभी भी सेटिंग्स में भाषा बदल सकते हैं",
    login: "लॉगिन",
    phoneNumber: "फ़ोन नंबर",
    enterPhone: "अपना 10 अंकों का फ़ोन नंबर दर्ज करें",
    sendOTP: "OTP भेजें",
    enterOTP: "OTP दर्ज करें",
    otpSent: "आपके फ़ोन पर OTP भेजा गया",
    verify: "सत्यापित करें और जारी रखें",
    dataSecure: "आपका डेटा हमारे पास सुरक्षित है",
    selectRole: "मैं एक हूं",
    farmer: "किसान",
    trader: "व्यापारी",
    namaste: "नमस्ते",
    todayWeather: "आज का मौसम",
    soilStatus: "मिट्टी की स्थिति",
    marketSnapshot: "बाजार भाव",
    quickActions: "त्वरित कार्य",
    joinMarket: "मार्केट रूम में शामिल हों",
    checkWeather: "मौसम देखें",
    soilIrrigation: "मिट्टी और सिंचाई",
    marketPrices: "बाजार भाव",
    financeManager: "वित्त प्रबंधक",
    home: "होम",
    market: "मार्केट",
    weather: "मौसम",
    finance: "वित्त",
    profile: "प्रोफाइल",
    activeTraders: "सक्रिय व्यापारी",
    highestBid: "सबसे ऊंची बोली",
    perQuintal: "प्रति क्विंटल",
    joinRoom: "रूम में शामिल हों",
    liveBids: "लाइव बोलियां",
    placeBid: "बोली लगाएं",
    yourContribution: "आपका योगदान",
    profitDistribution: "लाभ वितरण",
    transparency: "100% पारदर्शी",
    hourlyForecast: "घंटे के हिसाब से",
    weekForecast: "7 दिन का पूर्वानुमान",
    alerts: "अलर्ट",
    offlineCached: "ऑफ़लाइन डेटा उपलब्ध",
    soilMoisture: "मिट्टी की नमी",
    low: "कम",
    optimal: "सही",
    high: "ज़्यादा",
    irrigateNow: "अभी सिंचाई करें",
    waitHours: "6 घंटे रुकें",
    fertilizerTip: "उर्वरक सुझाव",
    trends: "ट्रेंड्स",
    mandiPrices: "मंडी भाव",
    pricePredict: "भाव अनुमान",
    compared: "कल की तुलना में",
    confidence: "विश्वसनीयता",
    loans: "आपके ऋण",
    amountBorrowed: "उधार ली गई राशि",
    interestRate: "ब्याज दर",
    nextEMI: "अगली EMI तारीख",
    govtSchemes: "सरकारी योजनाएं",
    bankLoans: "बैंक ऋण विकल्प",
    settings: "सेटिंग्स",
    changeLanguage: "भाषा बदलें",
    notifications: "सूचनाएं",
    iotStatus: "IoT डिवाइस स्थिति",
    helpSupport: "सहायता",
    logout: "लॉगआउट",
    connected: "कनेक्टेड",
    notConnected: "कनेक्ट नहीं",
    rainAlert: "कल बारिश की संभावना",
    delayIrrigation: "सिंचाई में देरी करें",
    heatAlert: "उच्च तापमान की संभावना",
    protectCrops: "शेड नेट से फसलों की रक्षा करें"
  },
  ta: {
    appName: "ஈஸ்ஃபார்மர்",
    tagline: "சிறந்த விவசாயத்திற்கான புத்திசாலித்தனமான முடிவுகள்",
    selectLanguage: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
    continue: "தொடரவும்",
    changeAnytime: "அமைப்புகளில் எப்போது வேண்டுமானாலும் மொழியை மாற்றலாம்",
    login: "உள்நுழைவு",
    phoneNumber: "தொலைபேசி எண்",
    enterPhone: "உங்கள் 10 இலக்க தொலைபேசி எண்ணை உள்ளிடவும்",
    sendOTP: "OTP அனுப்பு",
    enterOTP: "OTP உள்ளிடவும்",
    otpSent: "உங்கள் தொலைபேசிக்கு OTP அனுப்பப்பட்டது",
    verify: "சரிபார்த்து தொடரவும்",
    dataSecure: "உங்கள் தரவு எங்களிடம் பாதுகாப்பாக உள்ளது",
    selectRole: "நான் ஒரு",
    farmer: "விவசாயி",
    trader: "வியாபாரி",
    namaste: "வணக்கம்",
    todayWeather: "இன்றைய வானிலை",
    soilStatus: "மண் நிலை",
    marketSnapshot: "சந்தை விலைகள்",
    quickActions: "விரைவு செயல்கள்",
    joinMarket: "மார்க்கெட் அறையில் சேரவும்",
    checkWeather: "வானிலை பாருங்கள்",
    soilIrrigation: "மண் & நீர்ப்பாசனம்",
    marketPrices: "சந்தை விலைகள்",
    financeManager: "நிதி மேலாளர்",
    home: "முகப்பு",
    market: "சந்தை",
    weather: "வானிலை",
    finance: "நிதி",
    profile: "சுயவிவரம்",
    activeTraders: "செயலில் உள்ள வியாபாரிகள்",
    highestBid: "அதிக ஏலம்",
    perQuintal: "குவிண்டால்",
    joinRoom: "அறையில் சேரவும்",
    liveBids: "நேரடி ஏலங்கள்",
    placeBid: "ஏலம் விடுங்கள்",
    yourContribution: "உங்கள் பங்களிப்பு",
    profitDistribution: "லாப விநியோகம்",
    transparency: "100% வெளிப்படையானது",
    hourlyForecast: "மணிநேர முன்னறிவிப்பு",
    weekForecast: "7 நாள் முன்னறிவிப்பு",
    alerts: "எச்சரிக்கைகள்",
    offlineCached: "ஆஃப்லைன் தரவு கிடைக்கும்",
    soilMoisture: "மண் ஈரப்பதம்",
    low: "குறைவு",
    optimal: "சரியான",
    high: "அதிகம்",
    irrigateNow: "இப்போது நீர் பாய்ச்சுங்கள்",
    waitHours: "6 மணி நேரம் காத்திருங்கள்",
    fertilizerTip: "உர பரிந்துரை",
    trends: "போக்குகள்",
    mandiPrices: "மண்டி விலைகள்",
    pricePredict: "விலை கணிப்பு",
    compared: "நேற்றுடன் ஒப்பிடும்போது",
    confidence: "நம்பகத்தன்மை",
    loans: "உங்கள் கடன்கள்",
    amountBorrowed: "கடன் வாங்கிய தொகை",
    interestRate: "வட்டி விகிதம்",
    nextEMI: "அடுத்த EMI தேதி",
    govtSchemes: "அரசு திட்டங்கள்",
    bankLoans: "வங்கி கடன் விருப்பங்கள்",
    settings: "அமைப்புகள்",
    changeLanguage: "மொழியை மாற்றவும்",
    notifications: "அறிவிப்புகள்",
    iotStatus: "IoT சாதன நிலை",
    helpSupport: "உதவி & ஆதரவு",
    logout: "வெளியேறு",
    connected: "இணைக்கப்பட்டது",
    notConnected: "இணைக்கப்படவில்லை",
    rainAlert: "நாளை மழை எதிர்பார்க்கப்படுகிறது",
    delayIrrigation: "நீர்ப்பாசனத்தை தாமதப்படுத்தவும்",
    heatAlert: "அதிக வெப்பநிலை எதிர்பார்க்கப்படுகிறது",
    protectCrops: "நிழல் வலைகளால் பயிர்களைப் பாதுகாக்கவும்"
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('easefarmer_language') || 'en';
    }
    return 'en';
  });

  useEffect(() => {
    localStorage.setItem('easefarmer_language', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}